config/routes.rb
ProMyFlower::Application.routes.draw do
  get "tabcarts/addcart"
  get "tabusers/login"
  get "tabusers/register"
  get "tabuser/register"
  get "tabuser/login"
  match 'tabusers/register' => 'tabusers#register'
  match 'tabusers/registerUser' => 'tabusers#registerUser'
  match 'tabusers/login' => 'tabusers#login'
  match 'tabflowers/show'=>'tabflowers#show'
  match 'tabflowers/addcart'=>'tabflowers#addcart'
  match 'tabflowers/checkout'=>'tabflowers#checkout'
  match 'tabflowers/emptyFlower'=>'tabflowers#emptyFlower'
  match 'tabflowers/tjFriends'=>'tabflowers#tjFriends'
  match 'tabusers/exit' => 'tabusers#exit'
  match 'tabflowers/JZ'=>'tabflowers#JZ'
  match'tabflowers/search'=>'tabflowers#search'
  match'tabflowers/deleteFlower'=>'tabflowers#deleteFlower'
  match'tabflowers/updatecart'=>'tabflowers#updatecart'

  resources :tabflowers

end

app/models/tabflower.rb
class Tabflower < ActiveRecord::Base
end

app/models/tabuser.rb
class Tabuser < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tabcarts_controller.rb
class TabcartsController < ApplicationController
  def addcart
  end

end

app/controllers/tabflowers_controller.rb
class TabflowersController < ApplicationController
  # GET /tabflowers
  # GET /tabflowers.xml
  def index
#    @tabflowers = Tabflower.all
#     @tabflowers=Tabflower.paginate :page =>1, :per_page => 1
    @tabflowers=Tabflower.paginate :page => params[:page], :per_page => 9
    sql="select count(*) from tabflowers"
    @totalTS=Tabflower.count_by_sql(sql)
    totalTS=Tabflower.count_by_sql(sql)
    @currentYS=params[:page]
    @perPage=9
    perPage=9
    if totalTS % perPage!=0
      totalJY=totalTS / perPage+1
    else
      totalJY=totalTS / perPage
    end
    @totalJY=totalJY
    @tabuser=session[:tabuser]
      respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tabflowers }
    end
  end
    # GET /tabflowers/1
  # GET /tabflowers/1.xml
  def show
 @tabuser=session[:tabuser]
    @tabflower = Tabflower.find(params[:id])
 if @tabuser!=nil
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tabflower }
    end
    end
  end

  # GET /tabflowers/new
  # GET /tabflowers/new.xml
  def new

     @tabuser=session[:tabuser]
    if @tabuser!=nil then
    @tabflower = Tabflower.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tabflower }
    end
    end    
  end

  # GET /tabflowers/1/edit
  def edit
    @tabflower = Tabflower.find(params[:id])
  end

  # POST /tabflowers
  # POST /tabflowers.xml
  def create
     @tabuser=session[:tabuser]
    if @tabuser!=nil then
    @tabflower = Tabflower.new(params[:tabflower])
    respond_to do |format|
      if @tabflower.save
        format.html { redirect_to(@tabflower, :notice => 'Tabflower was successfully created.') }
        format.xml  { render :xml => @tabflower, :status => :created, :location => @tabflower }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tabflower.errors, :status => :unprocessable_entity }
      end
    end
    end    
  end

  # PUT /tabflowers/1
  # PUT /tabflowers/1.xml
  def update
    @tabflower = Tabflower.find(params[:id])
    respond_to do |format|
      if @tabflower.update_attributes(params[:tabflower])
        format.html { redirect_to(@tabflower, :notice => 'Tabflower was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tabflower.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tabflowers/1
  # DELETE /tabflowers/1.xml
  def destroy
    @tabflower = Tabflower.find(params[:id])
    @tabflower.destroy
    respond_to do |format|
      format.html { redirect_to(tabflowers_url) }
      format.xml  { head :ok }
    end
  end


  def addcart
    @tabuser=session[:tabuser]
    if @tabuser!=nil then
    tabflower=Tabflower.find(params[:id])
    if(session[:tabflower_shopping]==nil) then
      session[:tabflower_shopping]=Hash.new
    end
     tabflower_shop=session[:tabflower_shopping]
    if tabflower_shop.has_key?(tabflower) then
      tabflower_shop[tabflower]=tabflower_shop[tabflower]+1
    else
      tabflower_shop[tabflower]=1
    end
      redirect_to :action=>"checkout"
    else
     flash[:notice]="Please first to Login"
    end
  end  

  def checkout
     @tabuser=session[:tabuser]
     if @tabuser!=nil then
     @tabflower_shop=  session[:tabflower_shopping]
     @totalfp=0
     @totalfs=0
     if @tabflower_shop!=nil then
         @tabflower_shop.each do |tabflower,amount|
           if session[:amount]!=nil
             amount=session[:amount].to_i
           end
         @totalfp+=tabflower.fPprice*amount
         @totalfs+=tabflower.fSPrice*amount
         end
     end
     else
       flash[:notice]="You not Login"
     end
  end

  def emptyFlower
    @tabuser=session[:tabuser]
     if @tabuser!=nil then
    session[:tabflower_shopping]=nil
    redirect_to :action=>"checkout"
     end
  end

  def JZ
     @tabuser=session[:tabuser]
     if @tabuser!=nil then
     @tabflower_shop=  session[:tabflower_shopping]
     @totalfp=0
     @totalfs=0
     if @tabflower_shop!=nil then
         @tabflower_shop.each do |tabflower,amount|
         @totalfp+=tabflower.fPprice*amount
         @totalfs+=tabflower.fSPrice*amount
         end
     end
     else
       flash[:notice]="You not Login"
     end
  end

  def tjFriends
    @tabuser=session[:tabuser]
    if @tabuser==nil
      redirect_to :action=>"index"  
    end
  end

  def search
    searchName=params[:tabflower][:fName]
    sql="select * from tabflowers where fName like '%"+searchName+"%'"
    @tabflowers=Tabflower.find_by_sql(sql)
    if @tabflowers==nil
      flash[:notice]="sorry,this Flower is not store"
    end
  end


  def deleteFlower
    id=params[:id]
    @tabuser=session[:tabuser]
    if @tabuser!=nil then
    tabflower=Tabflower.find(params[:id])
    if(session[:tabflower_shopping]==nil) then
      session[:tabflower_shopping]=Hash.new
    end
     tabflower_shop=session[:tabflower_shopping]
    if tabflower_shop.has_key?(tabflower) then
    tabflower_shop.delete(tabflower)   
    end
      redirect_to :action=>"checkout"
    else
     flash[:notice]="Please first to Login"
    end
  end
end

app/controllers/tabusers_controller.rb
class TabusersController < ApplicationController
  def login
     uname=params[:tabuser][:uName]
     upass=params[:tabuser][:uPass]
     session[:tabuser]=nil
     user=Tabuser.find_by_uName_and_uPass(uname,upass)
    if user
      session[:tabuser]=user
      session[:tabuserId]=user.id
      @tabuser=session[:tabuser]
      redirect_to :action=>"index",:controller=>"tabflowers"
    else
      session[:tabuser]=nil
      flash[:notice]="denglushibai!"
    end
  end

  def register
  end

  def registerUser
    @new_user=Tabuser.new()
    @new_user.uName=params[:tabuser][:name]
    @new_user.uPass=params[:tabuser][:pass]
    @new_user.uTname=params[:tabuser][:tname]
    @new_user.uAddress=params[:tabuser][:address]
    @new_user.uCode=params[:tabuser][:code]
    @new_user.uPhone=params[:tabuser][:phone]
    @new_user.uEmail=params[:tabuser][:email]
    @new_user.uAddressType=params[:tabuser][:type]
    if @new_user.save
      redirect_to :action=>"register"
      flash[:notice]="恭喜您"+@new_user.uName+"，会员注册成功!"    
    end
  end

  def exit
    session[:tabuser]=nil
    redirect_to :action=>"index",:controller=>"tabflowers"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tabcarts_helper.rb
module TabcartsHelper
end

app/helpers/tabflowers_helper.rb
module TabflowersHelper
end

app/helpers/tabuser_helper.rb
module TabuserHelper
end

app/helpers/tabusers_helper.rb
module TabusersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProMyFlower</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body class="twoColFixLtHdr">
<div id="container">
  <div id="header">    
    <div class="bg" >
      <div class="divHead1"> <IMG border=0 src="/index/i2.gif"
                 width=64 height=22 /> <IMG border=0 src="/index/i3.gif"
                 width=63 height=22 /> <IMG border=0 src="/index/i4.gif"
                 width=63 height=22 /> <IMG border=0 src="/index/i5.gif"
                 width=86 height=22 /> <IMG border=0 src="/index/i6.gif"
                 width=86 height=22 /> <img border=0 src="/index/i7.gif"
                 width=86  height=22 /> <IMG border=0 src="/index/i8.gif"
                 width=90 height=22 /> </div>
      <div class="divHead2">
        <TABLE border=0 cellSpacing=0 cellPadding=0 align=left height=23>
          <TR align=middle>
            <TD vAlign=center background=/index/i13.gif width=73><A class=link href="#" >婚礼庆典</A>
            <TD vAlign=center background=/index/i13.gif width=73><A  class=link href="#" >购物指南</A></TD>
            <TD background=/index/i13.gif width=73><A class=link  href="#" >订单查询</A></TD>
            <TD background=/index/i13.gif width=73><A class=link  href="#" >节日提醒</A></TD>
            <TD background=/index/i13.gif width=73><A class=link href="#" >说话玫瑰</A></TD>
            <TD background=/index/i13.gif width=73><A class=link  href="#">自助订花</A></TD>
            <TD background=/index/i13.gif width=73><A class=link  href="#" >鲜花常识</A></TD>
            <TD background=/index/i13.gif width=73><A class=link href="#">团购服务</A></TD>
          </TR>
        </TABLE>
      </div>
      <div class="divHead3">
        <%form_tag "tabflowers/search" do %>
            <%= text_field :tabflower,:fName,:style=>"margin-top:-10px" ,:size=>4 %>       
         <%= submit_tag 'Go' %>
        <% end %>
      </div>
    </div>
    <!-- end #header -->
  </div>
  <div id="sidebar1">
    <% if @tabuser==nil then %>
    <div class="divleftLogin">
      <%form_tag "/tabusers/login"  do %>
      <div class="divleft1">
        <%= text_field :tabuser,:uName,:class=>"txt",:size=>"10" %>
        <div class="divTab"></div>
        <%= text_field :tabuser,:uPass,:class=>"txt" ,:size=>"12",:type=>"password"%>
      </div>

      <div class="divleftBtn">
        <%= submit_tag '',:class=>"Appbtn"%>
                               <a href="/tabusers/register">                                
                                 <IMG
                                border=0 src="/index/i18.gif" width=80
                                height=22></A> </div>
           <% end %>
      <div class="divleftCart"><a href="/tabflowers/checkout" class="link">查看购物车</a></div>
    </div>
    <div class="divleftShopp"> </div>
        <% else %>
    <div class="divleftLogin1">
      <div class="divleftLogin1CK"><font color="red" size="2";>您好， <%=@tabuser.uName %>:<br>&nbsp;&nbsp;您已经成功登录!
      </font><br>
     <font color="red"> 我们的宗旨是：<br>您就是我们的上帝</font>
        <% if @tabuser!=nil then %>
       <div style="margin-left:60px; padding-top:5px;"><a href="/tabusers/exit" class="link">退出</a></div>
          <% end %>
      </div>     
      <div class="divleftCart"><a href="/tabflowers/checkout" class="link">查看购物车</a></div>
    </div>
         <div class="divleftShopp"> </div>
        <% end %>
  </div>
  <div id="mainContent">
  <%= yield %>
  </div>
  <br class="clearfloat" />
  <div id="footer">
    <div class="divBottom"></div>
  </div>
  <!-- end #container -->
</div>
</body>
</html>

app/views/tabcarts/addcart.html.erb
<h1>Tabcarts#addcart</h1>
<p>Find me in app/views/tabcarts/addcart.html.erb</p>

app/views/tabflowers/JZ.html.erb
<h2><%=@tabuser.uName %>先生/小姐：您好!</h2>
<h3>您的消费金额为：<input type="text" value="<%=@totalfp %>"></h3>    <br>
<%= link_to '确认付账',{:action=>"index"},:class=>"registerDivBtn" %>

app/views/tabflowers/_form.html.erb
<%= form_for(@tabflower) do |f| %>
  <% if @tabflower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tabflower.errors.count, "error") %> prohibited this tabflower from being saved:</h2>

      <ul>
      <% @tabflower.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   名称：
    <%= f.text_field :fName %>
  </div>
  <div class="field">
   寓意：
    <%= f.text_field :fHanyi %>
  </div>
  <div class="field">
  价格：
    <%= f.text_field :fSPrice %>
  </div>
  <div class="field">
    编号：
    <%= f.text_field :fImg %>
  </div>
  <div class="field">
   详细：
    <%= f.text_field :fDetails %>
  </div>
  <div class="field">
   材料：
    <%= f.text_field :fCailiao %>
  </div>
  <div class="field">
   包装：
    <%= f.text_field :fBaoZ %>
  </div>
  <div class="field">
  价格：
    <%= f.text_field :fPprice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tabflowers/addcart.html.erb
<h2><%=notice %></h2>

app/views/tabflowers/checkout.html.erb
<div style="border:solid 1px #00994D; ">
  <table width="540px" border="0">
<tr class="cartBg">
  <td class="cartBgDivTab">商品编号</td>
  <td class="cartBgDivTab">商品名称</td>
  <td class="cartBgDivTab">商品数量</td>
  <td class="cartBgDivTab">市场价格</td>
  <td class="cartBgDivTab">会员价格</td>
  <td class="cartBgDivTab"></td>
  <td class="cartBgDivTab"></td>
</tr>
  <% if @tabflower_shop!=nil then %>
  <% @tabflower_shop.each do |tabflower,amount|%>
            <%form_tag :action=>:updatecart  do %>
            <tr>
<td><%=tabflower.id  %><%= text_field :tabflower,:id,:size=>0 ,:type=>"hidden" %></td>
    <td><%=tabflower.fName  %></td>
    <td><%= amount %></td>
    <td><%= tabflower.fPprice %></td>
    <td><%= tabflower.fSPrice %></td>
    <td>
    </td>
    <td>     
      <a href="/tabflowers/deleteFlower?id=<%=tabflower.id %>" class="registerDivBtn">删除</a>
    </td>
    </tr>
        <% end %>
      <% end %>
        <tr>
            <td></td>
            <td></td>      
            <td>合计：</td>
            <td><%= @totalfp %></td>
            <td><%= @totalfs %></td>
        </tr>
  <% else %>
  购物车已清空！
  <% end %>
    </tr>
<tr>
  <%= notice %>
  <td colspan="2">
 <%= link_to "清空购物车" ,{:action=>"emptyFlower"},:class=>"registerDivBtn" %> </td>
 <td colspan="2"><%= link_to '继 续 购 物',{:action=>'index'},:class=>"registerDivBtn" %></td>
  <td colspan="2"><%= link_to '收银台结账',{:action=>'JZ'},:class=>"registerDivBtn" %></td>
    </tr>
       </table>
</div>

app/views/tabflowers/edit.html.erb
<h1>Editing tabflower</h1>
<%= render 'form' %>
<%= link_to 'Show', @tabflower %> |
<%= link_to 'Back', tabflowers_path %>

app/views/tabflowers/index.html.erb
<% i=0 %>

<table style="border:solid 0px #F60" width="550px">
  <tr>
    <% @tabflowers.each do |tabflower| %>
    <td>
    <a href="/tabflowers/show?id=<%=tabflower.id %>" >
     <img src="/images/<%= tabflower.fImg %>.jpg" alt="" align="center" border="0" width="100px"></a><br/>
      名称：<%= tabflower.fName %><br/>
      <%= tabflower.fHanyi %><br>
      市场价格：<%= tabflower.fSPrice %>
      <br>
     <a href="/tabflowers/addcart?id=<%=tabflower.id %>"><img src="/index/i32.gif" alt="" border="0"></a>
    </td>
<% i=i+1 %>
<%if i%3==0 then%>
</tr>
   <tr>
  <%end %>
<% end %>
   </tr>
    <tr><td>共<%=@totalJY %>页，共<%= @totalTS %>条，每页显示<%=@perPage %>条</td><td><%= will_paginate @tabflowers,:prev_label=> "上一页",:next_label=>:"下一页" %></td></tr>
</table>
        <% if @tabuser!=nil then %>
    <% if @tabuser.uName=="dcy" then %>
<%= link_to '添加商品', new_tabflower_path,:class=>"registerDivBtn" %>
<% end %>
    <% end %>
<br />

app/views/tabflowers/new.html.erb
<h1>添加商品</h1>

<%= render 'form' %>

<%= link_to '返回', tabflowers_path %>

app/views/tabflowers/search.html.erb
<% i=0 %>
<table style="border:solid 0px #F60" width="550px">
  <tr>
    <% @tabflowers.each do |tabflower| %>
    <td>
    <a href="/tabflowers/show?id=<%=tabflower.id %>" >
     <img src="/images/<%= tabflower.fImg %>.jpg" alt="" align="center" border="0" width="100px"></a><br/>
      名称：<%= tabflower.fName %><br/>
      <%= tabflower.fHanyi %><br>
      市场价格：<%= tabflower.fSPrice %>
      <br>
     <a href="/tabflowers/addcart?id=<%=tabflower.id %>"><img src="/index/i32.gif" alt="" border="0"></a>
    </td>
<% i=i+1 %>
<%if i%3==0 then%>
</tr>
   <tr>
  <%end %>
<% end %>
   </tr>
    <tr><td><h2><%=notice %></h2></td></tr>
</table>
        <% if @tabuser!=nil then %>
    <% if @tabuser.uName=="dcy" then %>
<%= link_to '添加详情', new_tabflower_path,:class=>"registerDivBtn" %>
<% end %>
    <% end %>
<br />



app/views/tabflowers/show.html.erb
<div class="detailsBg">

  <div class="detailsBgLeft">

编号：<%= @tabflower.id %><div style="height:8px"></div>
名称：<%= @tabflower.fName %><div style="height:8px"></div>
花语：<%= @tabflower.fHanyi %><div style="height:8px"></div>
花才：<%= @tabflower.fCailiao %><div style="height:8px"></div>
包装：<%= @tabflower.fBaoZ %><div style="height:8px"></div>
详细信息： <%= @tabflower.fDetails %><div style="height:8px"></div>
市场价格： <%= @tabflower.fSPrice %><div style="height:8px"></div>
会员价格： <%= @tabflower.fPprice %><div style="height:8px"></div>
    <div style="height:8px"></div>
<div style="height:8px"></div>
   <%= link_to '放入购物车',{:action=>'addcart' ,:id=>@tabflower.id },:class=>"registerDivBtn"%>
   <%= link_to '推荐给朋友',{:action=>'tjFriends'},:class=>"registerDivBtn" %>
   <%= link_to '返回鲜花页面',{:action=>'index'},:class=>"registerDivBtn" %>
  </div>
  <div class="detailsBgRight"><img src="/images/<%= @tabflower.fImg %>.jpg" width="250px"></div>

</div>

app/views/tabuser/login.html.erb
<h1>Tabuser#login</h1>
<p>Find me in app/views/tabuser/login.html.erb</p>

app/views/tabuser/register.html.erb
<h1>Tabuser#register</h1>
<p>Find me in app/views/tabuser/register.html.erb</p>

app/views/tabusers/register.html.erb
<div class="registerbg">
  <div class="registertext">
    <%=form_tag :action=>:registerUser  do %>
      <%= text_field :tabuser,:name,:class=>"inputText",:size=>"12" %>
      <div class="registerDivTab"></div>
       <%= text_field :tabuser,:pass,:class=>"inputText",:size=>"14",:type=>"password" %>
      <div class="registerDivTab"></div>
      <input type="password" size="14"  class="inputText"/>
      <div class="registerDivTab"></div>
     <%= text_field :tabuser,:tname,:class=>"inputText",:size=>"27" %>
      <div class="registerDivTab"></div>
      <input type="text" size="27"  class="inputText"/>
      <div class="registerDivTab"></div>
      <input type="text" size="27"  class="inputText"/>
      <div class="registerDivTab"></div>
      <input type="text" size="27"  class="inputText"/>
      <div class="registerDivTab"></div>
      <%= text_field :tabuser,:address,:class=>"inputText",:size=>"27" %>
      <div class="registerDivTab"></div>
      <input type="text" size="27"  class="inputText"/>
      <div class="registerDivTab"></div>
      <input type="text" size="27"  class="inputText"/>
      <div class="registerDivTab"></div>
      <%= text_field :tabuser,:code,:class=>"inputText",:size=>"27" %>
      <div class="registerDivTab"></div>
      <%= text_field :tabuser,:phone,:class=>"inputText",:size=>"27" %>
      <div class="registerDivTab"></div>
      <%= text_field :tabuser,:email,:class=>"inputText",:size=>"27" %>
      <div class="registerDivTab"></div>
      <%= text_field :tabuser,:type,:class=>"inputText",:size=>"27" %>
      <div class="registerDivTab"></div>
        <%= submit_tag '提交',:class=>"registerDivBtn"%>
      <input type="button"  class="registerDivBtn" value="取消"/>
              <div><h2><%= notice %></h2></div>
    <% end %>
  </div>
</div>